name: Generate Snake

# Automatically run the action on pushes and on a schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # Runs every day at midnight

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Generate Contribution Snake
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: muhiddinovismoil
          github_token: ${{ secrets.GH_TOKEN }}
          # Generate multiple output types
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Commit and push the generated assets back to GitHub
      - name: Commit Generated Assets
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add dist/
          git commit -m "Update contribution snake"
          git push origin main
