name: Generate Contribution Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: muhiddinovismoil
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Commit Generated Assets
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add dist/
          git commit -m "Update contribution snake"
          git push origin main
